version: 2
jobs:
    build:
        working_directory: ~/PythonAutomationTraining
        docker:
            - image: circleci/python:3.7.2
              environment:
                  PIPENV_VENV_IN_PROJECT: true
        steps:
            - checkout
            
            - run:
                name: install dependencies
                command: |
                  python3 -m venv venv
                  . venv/bin/activate
                  pip install -r requirements.txt
            
            - run:
                command: |
                  sudo pip install pytest 
                  
            - run: 
                name: run tests 
                command: |
                  . venv/bin/activate
                  sudo pip install xmltodict
                  pytest -v
                  
            - store_artifacts:
                path: test-reports
                destination: test-reports
