version: 2
jobs:
    build:
        working_directory: ~/PythonAutomationTraining
        docker:
            - image: circleci/python:3.7.3-stretch-node-browsers
              environment:
                  PIPENV_VENV_IN_PROJECT: true
        steps:
            - checkout
            
            - run:
                name: Install Dependencies
                command: |
                  python3 -m venv venv
                  . venv/bin/activate
                  pip install -r requirements.txt

### Unnecessary since use venv in test run which contains all dependencies from previous step
#            - run:
#                command: |
#                  sudo pip install pytest
#                  sudo pip install allure-pytest
#                  sudo pip install selenium
#                  sudo pip install webdriver_manager

            - run:
                name: Install Allure CLI
                command: |
                  uname -a
                  sudo npm install -g allure-commandline --save-dev

            - run:
                name: Run API Tests
                command: |
                  . venv/bin/activate
                  pytest -v tests_api/test_update_issues.py --alluredir=./test-reports/allure

            - run:
                name: Run UI Tests
                command: |
                  . venv/bin/activate
                  pytest -v tests_ui/test_jira_login.py --alluredir=./test-reports/allure

            - run:
                name: Allure report
                when: always
                command: |
                  allure generate -c ./test-reports/allure -o ./test-reports/allure_html_reports

            - store_artifacts:
                path: test-reports
                destination: test-reports
